Add support for DELETE CASCADE and DELETE RESTRICT
Proof of concept of allowing a DELETE statement to override formal FK's handling from RESTRICT/NO
ACTION and treat as CASCADE instead and vice-versa

Syntax is "DELETE [ CASCADE | RESTRICT ] ..." instead of "DELETE ... [ CASCADE | RESTRICT ]" due to unresolvable bison conflicts.

Sample session:

  postgres=# create table foo (id serial primary key, val text);
  CREATE TABLE
  postgres=# create table bar (id serial primary key, foo_id int references foo(id), val text);
  CREATE TABLE
  postgres=# insert into foo (val) values ('a'),('b'),('c');
  INSERT 0 3
  postgres=# insert into bar (foo_id, val) values (1,'d'),(1,'e'),(2,'f'),(2,'g');
  INSERT 0 4
  postgres=# select * from foo;
   id | val
  ----+-----
    1 | a
    2 | b
    3 | c
  (3 rows)

  postgres=# select * from bar;
   id | foo_id | val
  ----+--------+-----
    1 |      1 | d
    2 |      1 | e
    3 |      2 | f
    4 |      2 | g
  (4 rows)

  postgres=# delete from foo where id = 1;
  ERROR:  update or delete on table "foo" violates foreign key constraint "bar_foo_id_fkey" on table "bar"
  DETAIL:  Key (id)=(1) is still referenced from table "bar".
  postgres=# delete cascade from foo where id = 1;
  DELETE 1
  postgres=# select * from foo;
   id | val
  ----+-----
    2 | b
    3 | c
  (2 rows)

  postgres=# select * from bar;
   id | foo_id | val
  ----+--------+-----
    3 |      2 | f
    4 |      2 | g
  (2 rows)